"""Wiki analysis — generate WIKI_REPORT.md with health metrics, hubs, gaps, freshness."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from oh_my_wiki.article import (
    Article,
    compute_backlink_counts,
    list_articles,
)
from oh_my_wiki.compile import load_compile_log
from oh_my_wiki.detect import detect
from oh_my_wiki.index import hub_articles


def generate_report(wiki_dir: Path, raw_dir: Path | None = None) -> str:
    """Generate WIKI_REPORT.md content."""
    articles = list_articles(wiki_dir)
    if not articles:
        return "# Wiki Report\n\n> Empty wiki.\n"

    now = datetime.now(timezone.utc)
    today = now.strftime("%Y-%m-%d")

    total_words = sum(a.word_count or len(a.body.split()) for a in articles)
    backlinks = compute_backlink_counts(wiki_dir)

    # Confidence breakdown
    conf_counts = {"high": 0, "medium": 0, "low": 0}
    for a in articles:
        conf_counts[a.confidence] = conf_counts.get(a.confidence, 0) + 1

    # Status breakdown
    status_counts: dict[str, int] = {}
    for a in articles:
        status_counts[a.status] = status_counts.get(a.status, 0) + 1

    # Categories
    categories: set[str] = set()
    for a in articles:
        categories.update(a.categories)

    # Raw corpus stats
    raw_words = 0
    raw_files = 0
    if raw_dir and raw_dir.exists():
        raw_result = detect(raw_dir)
        raw_words = raw_result["total_words"]
        raw_files = raw_result["total_files"]

    # Hub articles
    hubs = hub_articles(wiki_dir, top_n=10)

    # Stubs
    stubs = [a for a in articles if a.status == "stub"]

    # Orphans (0 backlinks, not stubs)
    orphans = [a for a in articles if backlinks.get(a.title, 0) == 0 and a.status != "stub"]

    # Freshness
    ages: list[int] = []
    for a in articles:
        if a.updated:
            try:
                updated = datetime.fromisoformat(a.updated.replace("Z", "+00:00"))
                age = (now - updated).days
                ages.append(age)
            except Exception:
                pass

    # Compile log
    compile_log = load_compile_log(wiki_dir.parent)

    # Build report
    lines = [
        f"# Wiki Report ({today})",
        "",
        "## Summary",
        f"- {len(articles)} articles · {total_words:,} words · {len(categories)} categories",
    ]

    if compile_log:
        lines.append(f"- Last compiled: {compile_log.get('timestamp', 'unknown')[:19]} ({compile_log.get('mode', 'unknown')})")

    if raw_files:
        lines.append(f"- Raw corpus: {raw_files} files · ~{raw_words:,} words")
        if raw_words > 0 and total_words > 0:
            ratio = raw_words / total_words
            lines.append(f"- Compression: {ratio:.1f}x (raw → wiki)")

    lines += [
        "",
        "## Health",
        f"- Confidence: {conf_counts.get('high', 0)} high, {conf_counts.get('medium', 0)} medium, {conf_counts.get('low', 0)} low",
    ]

    status_parts = []
    for s, count in sorted(status_counts.items()):
        status_parts.append(f"{count} {s}")
    lines.append(f"- Status: {', '.join(status_parts)}")

    if orphans:
        lines.append(f"- Orphans: {len(orphans)} articles with 0 backlinks")

    # Hub articles
    if hubs:
        lines += ["", "## Hub Articles (most backlinked)"]
        for i, h in enumerate(hubs, 1):
            lines.append(f"{i}. [[{h['title']}]] — {h['backlinks']} backlinks")

    # Coverage gaps
    gaps = []
    if stubs:
        stub_names = ", ".join(f"[[{s.title}]]" for s in stubs[:5])
        suffix = f" (+{len(stubs)-5} more)" if len(stubs) > 5 else ""
        gaps.append(f"- {len(stubs)} stub articles need source material: {stub_names}{suffix}")

    if orphans:
        orphan_names = ", ".join(f"[[{o.title}]]" for o in orphans[:5])
        suffix = f" (+{len(orphans)-5} more)" if len(orphans) > 5 else ""
        gaps.append(f"- {len(orphans)} orphan articles (0 backlinks): {orphan_names}{suffix}")

    if gaps:
        lines += ["", "## Coverage Gaps"] + gaps

    # Freshness
    if ages:
        oldest = max(ages)
        avg_age = sum(ages) // len(ages)
        recent = sum(1 for a in ages if a <= 7)
        lines += [
            "",
            "## Freshness",
            f"- Average article age: {avg_age} days",
            f"- Oldest article: {oldest} days",
            f"- Updated in last 7 days: {recent} articles",
        ]

    lines += [
        "",
        "---",
        "",
        "*Generated by [oh-my-wiki](https://github.com/andykhan/oh-my-wiki). See [[index]] to navigate.*",
    ]

    return "\n".join(lines)


def save_report(wiki_dir: Path, raw_dir: Path | None = None) -> Path:
    """Generate and save WIKI_REPORT.md."""
    report = generate_report(wiki_dir, raw_dir)
    path = wiki_dir / "WIKI_REPORT.md"
    path.write_text(report, encoding="utf-8")
    return path
