"""Index generation — index.md, category pages, hub article ranking."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from oh_my_wiki.article import (
    Article,
    compute_backlink_counts,
    list_articles,
    parse_frontmatter,
    safe_filename,
)


def wiki_status(wiki_dir: Path) -> dict:
    """Get current wiki status — article count, words, categories, health."""
    if not wiki_dir.exists():
        return {"exists": False, "total_articles": 0, "total_words": 0, "categories": []}

    articles = list_articles(wiki_dir)
    total_words = sum(a.word_count or len(a.body.split()) for a in articles)

    categories: set[str] = set()
    stubs = 0
    stale = 0
    for a in articles:
        categories.update(a.categories)
        if a.status == "stub":
            stubs += 1
        if a.status == "stale":
            stale += 1

    return {
        "exists": True,
        "total_articles": len(articles),
        "total_words": total_words,
        "categories": sorted(categories),
        "stubs": stubs,
        "stale": stale,
    }


def rebuild_index(wiki_dir: Path) -> dict:
    """Rebuild index.md and category pages. Returns stats dict.

    This is fully deterministic — no LLM needed.
    """
    wiki_dir.mkdir(parents=True, exist_ok=True)
    articles = list_articles(wiki_dir)

    if not articles:
        (wiki_dir / "index.md").write_text(
            "# Knowledge Base Index\n\n> Empty wiki. Run `omw compile` to build.\n"
        )
        return {"total_articles": 0, "total_words": 0, "total_categories": 0}

    # Compute backlink counts
    backlink_counts = compute_backlink_counts(wiki_dir)

    # Update backlink_count in each article's frontmatter
    for article in articles:
        count = backlink_counts.get(article.title, 0)
        if count != article.backlink_count:
            article.backlink_count = count
            # Rewrite file with updated count
            filename = safe_filename(article.title) + ".md"
            path = wiki_dir / filename
            if path.exists():
                path.write_text(article.to_markdown(), encoding="utf-8")

    # Gather stats
    total_words = sum(a.word_count or len(a.body.split()) for a in articles)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Group by category
    by_category: dict[str, list[Article]] = {}
    for a in articles:
        for cat in (a.categories or ["uncategorized"]):
            by_category.setdefault(cat, []).append(a)

    # Sort articles for various sections
    by_updated = sorted(articles, key=lambda a: a.updated or "", reverse=True)
    by_backlinks = sorted(articles, key=lambda a: a.backlink_count, reverse=True)
    by_title = sorted(articles, key=lambda a: a.title.lower())

    # --------------- Build index.md ---------------
    lines: list[str] = [
        "# Knowledge Base Index",
        "",
        f"> {len(articles)} articles · {total_words:,} words · Last compiled {now}",
        "",
        "## Categories",
        "",
    ]

    for cat in sorted(by_category, key=lambda c: -len(by_category[c])):
        count = len(by_category[cat])
        lines.append(f"- [[_categories/{cat}]] — {count} article{'s' if count != 1 else ''}")
    lines.append("")

    # Recent updates (top 10)
    lines.append("## Recent Updates")
    lines.append("")
    for a in by_updated[:10]:
        date_str = a.updated[:10] if a.updated else "unknown"
        lines.append(f"- [[{a.title}]] — {a.status} {date_str}")
    lines.append("")

    # Most connected (top 10)
    if any(a.backlink_count > 0 for a in articles):
        lines.append("## Most Connected")
        lines.append("")
        for a in by_backlinks[:10]:
            if a.backlink_count > 0:
                lines.append(f"- [[{a.title}]] — {a.backlink_count} backlink{'s' if a.backlink_count != 1 else ''}")
        lines.append("")

    # All articles A-Z
    lines.append("## All Articles")
    lines.append("")
    for a in by_title:
        cat_str = a.categories[0] if a.categories else "uncategorized"
        src_count = len(a.sources) if a.sources else 0
        conf = a.confidence or "medium"
        lines.append(f"- [[{a.title}]] — {cat_str} · {src_count} source{'s' if src_count != 1 else ''} · {conf}")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by [oh-my-wiki](https://github.com/andykhan/oh-my-wiki)*")

    (wiki_dir / "index.md").write_text("\n".join(lines), encoding="utf-8")

    # --------------- Build category pages ---------------
    cat_dir = wiki_dir / "_categories"
    cat_dir.mkdir(exist_ok=True)

    for cat, cat_articles in by_category.items():
        cat_sorted = sorted(cat_articles, key=lambda a: a.title.lower())
        cat_lines = [
            f"# {cat.title()}",
            "",
            f"> {len(cat_articles)} article{'s' if len(cat_articles) != 1 else ''}.",
            "",
            "## Articles",
            "",
        ]
        for a in cat_sorted:
            # Get first line of body as summary
            summary = _extract_summary(a)
            cat_lines.append(f"- [[{a.title}]] — {summary}")
        cat_lines.append("")
        cat_lines.append("---")
        cat_lines.append(f"*See [[index]] to navigate.*")

        (cat_dir / f"{safe_filename(cat)}.md").write_text(
            "\n".join(cat_lines), encoding="utf-8"
        )

    # Clean up empty/stale category pages
    current_cats = {safe_filename(c) + ".md" for c in by_category}
    for f in cat_dir.glob("*.md"):
        if f.name not in current_cats:
            f.unlink()

    return {
        "total_articles": len(articles),
        "total_words": total_words,
        "total_categories": len(by_category),
    }


def _extract_summary(article: Article) -> str:
    """Extract the one-line summary from an article body (blockquote after H1)."""
    for line in article.body.splitlines():
        line = line.strip()
        if line.startswith("> "):
            return line[2:].strip()
    # Fallback: first non-empty, non-heading line
    for line in article.body.splitlines():
        line = line.strip()
        if line and not line.startswith("#") and not line.startswith("---"):
            return line[:120]
    return ""


def hub_articles(wiki_dir: Path, top_n: int = 10) -> list[dict]:
    """Return the most-backlinked articles — the "god nodes" of the wiki."""
    counts = compute_backlink_counts(wiki_dir)
    sorted_articles = sorted(counts.items(), key=lambda x: -x[1])
    return [
        {"title": title, "backlinks": count}
        for title, count in sorted_articles[:top_n]
        if count > 0
    ]
